# Generated by Django 4.2 on 2024-07-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_network", "0002_alter_element_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(0, 0), (1, 1), (2, 2)], verbose_name="Уровень"
            ),
        ),
    ]
